pipeline {
    agent any

    stages {
        stage('Git Clone') {
            steps {
                git branch: 'master', url: 'https://github.com/cser-manish-rander/sample_java.git'
            }
        }

        stage('Compile Java') {
            steps {
                bat 'javac Test.java'
            }
        }

        stage('Run Java') {
            steps {
                bat 'java Test'
            }
        }

        stage('Hello') {
            steps {
                echo 'Hello World'
            }
        }
    }
}